#!/bin/sh
printf "Synchronizing disk writes..."; sync; printf " Done.\n"
PKG_ORPHANS="$(echo $(pacman -Qdttq))"
if [ ! -z "$PKG_ORPHANS" ]; then
	echo "The following dependencies are no longer required by any explicitly installed packages,"
	echo "use \"sudo pacman -Rus <PACKAGES>\" to remove them:"
	echo "$PKG_ORPHANS"
fi
