#!/bin/bash
ARCHISO_PROFILE="$1"
[ -z "$1" ] && ARCHISO_PROFILE="zestiso-kde"
MEM_MB_SIZE=$(free -m | grep "Mem:" | xargs | cut -d ' ' -f 2)
if [ $MEM_MB_SIZE -ge 20480 ]; then
	ARCHISO_WORK_DIR="/tmp/archiso-tmp"
else ARCHISO_WORK_DIR="work"; fi

echo "Preparing for build..."
sudo rm -rf out
sudo mkarchiso -v -w "$ARCHISO_WORK_DIR" "$ARCHISO_PROFILE" && sync && \
sudo chown -R $(whoami):$(whoami) out && cd out && \
mkdir -p ../../zestiso-iso && mv *.iso ../../zestiso-iso && \
cd ../ && echo "Cleaning up..." && sudo rm -rf out /tmp/archiso-tmp
sync
