#!/bin/sh
ISO_OUT_DIR="/run/media/am/Ventoy"
ARCHISO_PROFILE="$1"
[ -z "$1" ] && ARCHISO_PROFILE="zestiso-kde"
MEM_MB_SIZE=$(free -m | grep "Mem:" | xargs | cut -d ' ' -f 2)
if [ $MEM_MB_SIZE -ge 20480 ]; then
	ARCHISO_WORK_DIR="/tmp/archiso-tmp"
else ARCHISO_WORK_DIR="work"; fi
echo "BUILD ISO: $(date)"
sudo rm -rf out
sudo mkarchiso -v -w "$ARCHISO_WORK_DIR" "$ARCHISO_PROFILE" && sync && \
sudo chown -R $(whoami):$(whoami) out && cd out && \
mkdir -p "$ISO_OUT_DIR" && mv *.iso "$ISO_OUT_DIR" && \
cd ../ && rmdir out && sudo rm -rf $ARCHISO_WORK_DIR && \
echo "ISO BUILT: $(date)"
sync
